name = "App-bsky"
badges = ["github-actions/ci.yml", "metacpan"]
module_maker="ModuleBuildTiny"
static_install = "auto"
authority = "cpan:SANKO"
license = "artistic_2"
markdown_maker = "Pod::Markdown::Github"
readme_from = "script/bsky"

[release]
hooks=[
    'tidyall -a'
]

[no_index]
directory=[
    "t",
    "xt",
    "inc",
    "share",
    "eg",
    "examples",
    "author"
]

[Metadata]
X_No_Archive = 'Yes'
