---
jobs:
  build:
    name: 'Perl ${{ matrix.perl }} on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '${{ matrix.perl }}'
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends --mirror http://cpan.cpantesters.org/ .
      - name: Run test
        run: prove -lr t
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        perl:
          - "5.40"
name: CI
on:
  pull_request:
    branches: '*'
  push:
    branches: '*'
  schedule:
    - cron: 42 5 * * 0
  workflow_dispatch: ~
